name = "TrustPilotCalc"
uuid = "64a7c805-51c3-461c-bbc0-80a265aaf057"
authors = ["Val Lyashov <val@plstr.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
